name: multi-command-demo

on: push

jobs:
  my-lob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run multiple Commands
        run: |
          echo "First"
          echo "second"
          ls -la
